<#
provision.ps1 - one-shot, idempotent Azure provisioning for the live prototype (PowerShell).
Windows-native equivalent of provision.sh. Creates: AI Services (OpenAI) account + 4
deployments + Entra RBAC, and (optional) App Configuration + Application Insights, then
writes ..\.env for you.

Prereqs:  az login   (then optionally: az account set --subscription <id>)
Run from the repository root:
    pwsh infra/provision.ps1
    # or override defaults:
    pwsh infra/provision.ps1 -Loc swedencentral -Acct myaoai -DeployOptional:$false
#>

[CmdletBinding()]
param(
  [string]$Rg           = $(if ($env:RG)   { $env:RG }   else { 'rg-tokengov' }),
  [string]$Loc          = $(if ($env:LOC)  { $env:LOC }  else { 'eastus2' }),   # Model Router GA: eastus2 | swedencentral
  [string]$Acct         = $(if ($env:ACCT) { $env:ACCT } else { 'tokengov-aoai' }),
  [string]$AppCfg       = 'tokengov-appcfg',
  [string]$AppIns       = 'tokengov-ai',
  [bool]  $DeployOptional = $true,

  # Model names/versions change over time - verify with:
  #   az cognitiveservices account list-models -n <acct> -g <rg> -o table
  [string]$CheapModel   = 'gpt-4o-mini',            [string]$CheapVer  = '2024-07-18',
  [string]$PremModel    = 'gpt-4o',                 [string]$PremVer   = '2024-11-20',
  [string]$RouterModel  = 'model-router',           [string]$RouterVer = '2025-11-18',
  [string]$EmbedModel   = 'text-embedding-3-small', [string]$EmbedVer  = '1'
)

$ErrorActionPreference = 'Stop'

Write-Host "==> subscription: $(az account show --query name -o tsv)"
az group create -n $Rg -l $Loc -o none
Write-Host "==> resource group '$Rg' ready ($Loc)"

# Account (custom domain required for Entra ID / keyless auth)
az cognitiveservices account create -n $Acct -g $Rg -l $Loc `
  --kind AIServices --sku S0 --custom-domain $Acct -o none 2>$null
if ($LASTEXITCODE -ne 0) { az cognitiveservices account show -n $Acct -g $Rg -o none }
Write-Host "==> account '$Acct' ready"

function Deploy-Model {
  param([string]$Name, [string]$Model, [string]$Ver, [string]$Sku = 'Standard', [int]$Cap = 50)
  az cognitiveservices account deployment create -g $Rg -n $Acct `
    --deployment-name $Name --model-name $Model --model-version $Ver `
    --model-format OpenAI --sku-name $Sku --sku-capacity $Cap -o none 2>$null
  if ($LASTEXITCODE -eq 0) {
    Write-Host "   deployed '$Name' ($Model $Ver, $Sku)"
  } else {
    Write-Host "   WARN: '$Name' failed - check model/version/region/quota:"
    Write-Host "         az cognitiveservices account list-models -n $Acct -g $Rg -o table"
  }
}
Deploy-Model -Name 'gpt-cheap'    -Model $CheapModel  -Ver $CheapVer
Deploy-Model -Name 'gpt-premium'  -Model $PremModel   -Ver $PremVer
Deploy-Model -Name 'model-router' -Model $RouterModel -Ver $RouterVer -Sku 'GlobalStandard'
Deploy-Model -Name 'text-embed'   -Model $EmbedModel  -Ver $EmbedVer

# Entra ID data-plane RBAC (no keys)
$me    = az ad signed-in-user show --query id -o tsv
$scope = az cognitiveservices account show -n $Acct -g $Rg --query id -o tsv
az role assignment create --assignee $me --role "Cognitive Services OpenAI User" `
  --scope $scope -o none 2>$null
if ($LASTEXITCODE -eq 0) { Write-Host "==> RBAC granted" } else { Write-Host "==> RBAC already present" }

$endpoint = az cognitiveservices account show -n $Acct -g $Rg --query properties.endpoint -o tsv

$appcfgEp = ''; $appinsCs = ''
if ($DeployOptional) {
  az appconfig create -n $AppCfg -g $Rg -l $Loc --sku standard -o none 2>$null
  $appcfgEp = az appconfig show -n $AppCfg -g $Rg --query endpoint -o tsv 2>$null
  $cfgId    = az appconfig show -n $AppCfg -g $Rg --query id -o tsv 2>$null
  if ($cfgId) {
    az role assignment create --assignee $me --role "App Configuration Data Owner" `
      --scope $cfgId -o none 2>$null
  }
  az monitor app-insights component create --app $AppIns -g $Rg -l $Loc -o none 2>$null
  $appinsCs = az monitor app-insights component show --app $AppIns -g $Rg `
    --query connectionString -o tsv 2>$null
  Write-Host "==> optional: App Configuration + Application Insights ready"
}

$envFile = Join-Path (Split-Path -Parent $PSScriptRoot) '.env'
if (Test-Path $envFile) { Copy-Item $envFile "$envFile.bak" -Force; Write-Host "==> backed up existing .env -> .env.bak" }

@"
# Generated by infra/provision.ps1 - fill real PRICE_* from the Azure pricing page.
AZURE_OPENAI_ENDPOINT=$endpoint
AZURE_OPENAI_API_VERSION=2024-10-21
AZURE_DEPLOYMENT_CHEAP=gpt-cheap
AZURE_DEPLOYMENT_PREMIUM=gpt-premium
AZURE_DEPLOYMENT_ROUTER=model-router
AZURE_DEPLOYMENT_JUDGE=gpt-premium
AZURE_DEPLOYMENT_EMBEDDING=text-embed
PRICE_CHEAP_INPUT=0.00015
PRICE_CHEAP_OUTPUT=0.0006
PRICE_PREMIUM_INPUT=0.0025
PRICE_PREMIUM_OUTPUT=0.01
PRICE_ROUTER_INPUT_MARKUP=0.0
AZURE_APPCONFIG_ENDPOINT=$appcfgEp
APPLICATIONINSIGHTS_CONNECTION_STRING=$appinsCs
LIVE_MAX_REQUESTS=20
LIVE_WORKLOAD_REPEATS=3
"@ | Set-Content -Path $envFile -Encoding utf8

Write-Host ""
Write-Host "==> wrote $envFile"
Write-Host "==> NEXT:  pip install -r requirements.txt  ;  python demo.py --live"
Write-Host "==> (update PRICE_* with the real per-1K prices for your deployed models)"
