#!/usr/bin/env bash
# provision.sh - one-shot, idempotent Azure provisioning for the live prototype.
# Creates: AI Services (OpenAI) account + 4 deployments + Entra RBAC, and (optional)
# App Configuration + Application Insights. Then writes ../.env for you.
#
# Prereqs:  az login  &&  az account set --subscription <id>
# Run:      bash infra/provision.sh         (from the 06_prototype folder)
#
# Override any default via env, e.g.:  LOC=swedencentral ACCT=myaoai bash infra/provision.sh
set -euo pipefail

RG="${RG:-rg-tokengov}"
LOC="${LOC:-eastus2}"                 # Model Router GA regions: eastus2 | swedencentral
ACCT="${ACCT:-tokengov-aoai}"
APPCFG="${APPCFG:-tokengov-appcfg}"
APPINS="${APPINS:-tokengov-ai}"
DEPLOY_OPTIONAL="${DEPLOY_OPTIONAL:-true}"   # also create App Config + App Insights

# Model names/versions change over time - verify with:
#   az cognitiveservices account list-models -n "$ACCT" -g "$RG" -o table
CHEAP_MODEL="${CHEAP_MODEL:-gpt-4o-mini}";              CHEAP_VER="${CHEAP_VER:-2024-07-18}"
PREM_MODEL="${PREM_MODEL:-gpt-4o}";                     PREM_VER="${PREM_VER:-2024-11-20}"
ROUTER_MODEL="${ROUTER_MODEL:-model-router}";          ROUTER_VER="${ROUTER_VER:-2025-11-18}"
EMBED_MODEL="${EMBED_MODEL:-text-embedding-3-small}";  EMBED_VER="${EMBED_VER:-1}"

echo "==> subscription: $(az account show --query name -o tsv)"
az group create -n "$RG" -l "$LOC" -o none
echo "==> resource group '$RG' ready ($LOC)"

# Account (custom domain is required for Entra ID / keyless auth)
az cognitiveservices account create -n "$ACCT" -g "$RG" -l "$LOC" \
  --kind AIServices --sku S0 --custom-domain "$ACCT" -o none 2>/dev/null \
  || az cognitiveservices account show -n "$ACCT" -g "$RG" -o none
echo "==> account '$ACCT' ready"

deploy() {  # name model version [sku] [capacity]
  local name="$1" model="$2" ver="$3" sku="${4:-Standard}" cap="${5:-50}"
  if az cognitiveservices account deployment create -g "$RG" -n "$ACCT" \
       --deployment-name "$name" --model-name "$model" --model-version "$ver" \
       --model-format OpenAI --sku-name "$sku" --sku-capacity "$cap" -o none 2>/dev/null; then
    echo "   deployed '$name' ($model $ver, $sku)"
  else
    echo "   WARN: '$name' failed - check model/version/region/quota:"
    echo "         az cognitiveservices account list-models -n $ACCT -g $RG -o table"
  fi
}
deploy gpt-cheap    "$CHEAP_MODEL"  "$CHEAP_VER"
deploy gpt-premium  "$PREM_MODEL"   "$PREM_VER"
deploy model-router "$ROUTER_MODEL" "$ROUTER_VER" GlobalStandard
deploy text-embed   "$EMBED_MODEL"  "$EMBED_VER"

# Entra ID data-plane RBAC (no keys)
ME=$(az ad signed-in-user show --query id -o tsv)
SCOPE=$(az cognitiveservices account show -n "$ACCT" -g "$RG" --query id -o tsv)
az role assignment create --assignee "$ME" --role "Cognitive Services OpenAI User" \
  --scope "$SCOPE" -o none 2>/dev/null && echo "==> RBAC granted" || echo "==> RBAC already present"

ENDPOINT=$(az cognitiveservices account show -n "$ACCT" -g "$RG" --query properties.endpoint -o tsv)

APPCFG_EP=""; APPINS_CS=""
if [ "$DEPLOY_OPTIONAL" = "true" ]; then
  az appconfig create -n "$APPCFG" -g "$RG" -l "$LOC" --sku standard -o none 2>/dev/null || true
  APPCFG_EP=$(az appconfig show -n "$APPCFG" -g "$RG" --query endpoint -o tsv 2>/dev/null || echo "")
  CFG_ID=$(az appconfig show -n "$APPCFG" -g "$RG" --query id -o tsv 2>/dev/null || echo "")
  [ -n "$CFG_ID" ] && az role assignment create --assignee "$ME" \
    --role "App Configuration Data Owner" --scope "$CFG_ID" -o none 2>/dev/null || true
  az monitor app-insights component create --app "$APPINS" -g "$RG" -l "$LOC" -o none 2>/dev/null || true
  APPINS_CS=$(az monitor app-insights component show --app "$APPINS" -g "$RG" \
    --query connectionString -o tsv 2>/dev/null || echo "")
  echo "==> optional: App Configuration + Application Insights ready"
fi

ENVFILE="$(cd "$(dirname "$0")/.." && pwd)/.env"
[ -f "$ENVFILE" ] && cp "$ENVFILE" "$ENVFILE.bak" && echo "==> backed up existing .env -> .env.bak"
cat > "$ENVFILE" <<EOF
# Generated by infra/provision.sh - fill real PRICE_* from the Azure pricing page.
AZURE_OPENAI_ENDPOINT=$ENDPOINT
AZURE_OPENAI_API_VERSION=2024-10-21
AZURE_DEPLOYMENT_CHEAP=gpt-cheap
AZURE_DEPLOYMENT_PREMIUM=gpt-premium
AZURE_DEPLOYMENT_ROUTER=model-router
AZURE_DEPLOYMENT_JUDGE=gpt-premium
AZURE_DEPLOYMENT_EMBEDDING=text-embed
PRICE_CHEAP_INPUT=0.00015
PRICE_CHEAP_OUTPUT=0.0006
PRICE_PREMIUM_INPUT=0.0025
PRICE_PREMIUM_OUTPUT=0.01
PRICE_ROUTER_INPUT_MARKUP=0.0
AZURE_APPCONFIG_ENDPOINT=$APPCFG_EP
APPLICATIONINSIGHTS_CONNECTION_STRING=$APPINS_CS
LIVE_MAX_REQUESTS=20
LIVE_WORKLOAD_REPEATS=3
EOF

echo ""
echo "==> wrote $ENVFILE"
echo "==> NEXT:  pip install -r requirements.txt  &&  python demo.py --live"
echo "==> (update PRICE_* with the real per-1K prices for your deployed models)"
